version: "3"

services:
  reports:
    build:
      context: ../SistemaDeclaraciones_reportes
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - 3010:3010
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.11.1
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_SEARCH_PASSWORD
      - xpack.security.enabled=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    network_mode: host # Comentar o remover línea para desplegar en Windows/MacOS
    depends_on:
      - elasticsearch
      - reports
    volumes:
      - .:/usr/app
    #ports:           # Descomentar para desplegar en Windows/MacOS
    #  - 3000:3000    # Descomentar para desplegar en Windows/MacOS

volumes:
  esdata:
