version: "3"

services:
  reports:
    build:
      context: ../SistemaDeclaraciones_reportes
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - 3010:3010
    restart: unless-stopped

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    network_mode: host # Comentar o remover línea para desplegar en Windows/MacOS
    depends_on:
      # - elasticsearch
      - reports
    volumes:
      - .:/usr/app
    #ports:           # Descomentar para desplegar en Windows/MacOS
    #  - 3000:3000    # Descomentar para desplegar en Windows/MacOS

volumes:
  esdata:
